config/routes.rb
Rails.application.routes.draw do
  resources :thoughts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'thoughts#index'

  post '/thought/:thougth_id/observation/', to: 'observations#create', as: 'create_observation'

  get 'react/:reactable_type/:reactable_id/:reaction', to: 'reacts#react'
  get 'react-delete/:reactable_type/:reactable_id', to: 'reacts#remove_reaction'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/concerns/reactable.rb
module Reactable
  extend ActiveSupport::Concern

  included do
    has_many :reacts, as: :reactable
  end

  def react(reaction, current_user)
    React.create(reactable: self, user: current_user, reaction: reaction)
  end

  def react?(current_user)
    set_react(current_user)
    @react.present? ? @react : false
  end

  def update_react(reaction, current_user)
    set_react(current_user)
    @react.update(reaction: reaction)
  end

  def remove_reaction(current_user)
    set_react(current_user)
    @react.destroy
  end

  private

  def set_react(current_user)
    @react = React.find_by(reactable: self, user: current_user)
  end
end

app/models/react.rb
class React < ApplicationRecord
  belongs_to :reactable, polymorphic: true
  belongs_to :user

  enum reaction: %i[agree love disagree]
end

app/models/thought.rb
class Thought < ApplicationRecord

	include Reactable
	
	belongs_to :user

	acts_as_commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :set_thought
  def create
    observation = @thought.comments.create( comment: params[:comment], user: current_user )
    observation.save
    redirect_to thought_path(@thought.id)
  end
 
  private
 
    def set_thought
      @thought = Thought.find(params[:thougth_id])
    end
end

app/controllers/reacts_controller.rb
class ReactsController < ApplicationController
  before_action :set_reactable
 
  def react
    if @reactable.react?(current_user)
      @reactable.update_react(params[:reaction], current_user)
    else
      @reactable.react(params[:reaction], current_user)
    end
  end
 
  def remove_reaction
    @reactable.remove_reaction(current_user)
  end
 
  private
 
    def set_reactable
      reactable_type = params[:reactable_type]
      @reactable = reactable_type.constantize.find(params[:reactable_id])
    end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :set_thought, only: [:show, :edit, :update, :destroy]

  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
    @observations = @thought.comments.recent
  end

  # GET /thoughts/new
  def new
    @thought = Thought.new
  end

  # GET /thoughts/1/edit
  def edit
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = Thought.new(thought_params)
    @thought.user = current_user
    respond_to do |format|
      if @thought.save
        format.html { redirect_to @thought, notice: 'Thought was successfully created.' }
        format.json { render :show, status: :created, location: @thought }
      else
        format.html { render :new }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    respond_to do |format|
      if @thought.update(thought_params)
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought }
      else
        format.html { render :edit }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought.destroy
    respond_to do |format|
      format.html { redirect_to thoughts_url, notice: 'Thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      @thought = Thought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thought_params
      params.require(:thought).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/helpers/reacts_helper.rb
module ReactsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ShareThoughts</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/reacts/react.js.erb
$('#t-concordo, #t-amei, #t-discordo').attr({class:"btn btn-default btn-circle btn-lg"})
$('#t-concordo').attr({
  href:"/react/<%= @reactable.class.name %>/<%= @reactable.id %>/agree"
});
$('#t-amei').attr({
  href:"/react/<%= @reactable.class.name %>/<%= @reactable.id %>/love"
});
$('#t-discordo').attr({
  href:"/react/<%= @reactable.class.name %>/<%= @reactable.id %>/disagree"
});

<% if @reactable.react?(current_user) %>
  switch("<%= @reactable.react?(current_user).reaction %>") {
  case 'agree':
    $('#t-concordo').attr({ href:"/react-delete/<%= @reactable.class.name %>/<%=@reactable.id %>",
    class:"btn btn-info btn-circle btn-lg"
  });
  break;
  case 'love':
    $('#t-amei').attr({ href:"/react-delete/<%= @reactable.class.name %>/<%=@reactable.id %>",
    class:"btn btn-danger btn-circle btn-lg"
  });
  break;
  case 'disagree':
    $('#t-discordo').attr({ href:"/react-delete/<%= @reactable.class.name %>/<%=@reactable.id %>",
    class:"btn btn-warning btn-circle btn-lg"
  });
  break;
}
<% end %>

app/views/reacts/remove_reaction.js.erb
$('#t-concordo, #t-amei, #t-discordo').attr({class:"btn btn-default btn-circle btn-lg"})
$('#t-concordo').attr({
  href:"/react/<%= @reactable.class.name %>/<%= @reactable.id %>/agree"
});
$('#t-amei').attr({
  href:"/react/<%= @reactable.class.name %>/<%= @reactable.id %>/love"
});
$('#t-discordo').attr({
  href:"/react/<%= @reactable.class.name %>/<%= @reactable.id %>/disagree"
});

app/views/thoughts/_form.html.erb
<%= form_for @thought, :html => { :class => "form-horizontal thought" } do |f| %>

  <% if @thought.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@thought.errors.count, "error") %> prohibited this thought from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @thought.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :body, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :body, :class => 'form-control' %>
    </div>
    <%=f.error_span(:body) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                thoughts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/thoughts/edit.html.erb
<%- model_class = Thought -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/thoughts/index.html.erb
<%- model_class = Thought -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th>author</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @thoughts.each do |thought| %>
      <tr>
        <td><%= thought.title %></td>
        <td><%= thought.user.email %></td>
        <td><%=l thought.created_at %></td>
        <td>

          <%= link_to t('.show', :default => t("helpers.links.show")),
                      thought_path(thought), :class => 'btn btn-default btn-xs' %>
          <% if thought.user == current_user %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_thought_path(thought), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        thought_path(thought),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_thought_path,
            :class => 'btn btn-primary' %>

app/views/thoughts/new.html.erb
<%- model_class = Thought -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/thoughts/show.html.erb
<div class="container">
  <div class="page-header">
    <div class="row">
      <div class="col-lg-8">
        <h1><%= @thought.title %></h1>
      </div>
      <div class="col-lg-4 text-right">
        <%= link_to t('.back', :default => t("helpers.links.back")),
                      thoughts_path, :class => 'btn btn-default'  %>
        <% if @thought.user == current_user %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_thought_path(@thought), :class => 'btn btn-default' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        thought_path(@thought),
                        :method => 'delete',
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8">
      <blockquote>
      <p><%= @thought.body %></p>
      <footer>written by <cite title="Source Title"><%= @thought.user.email %></cite></footer>
    </blockquote>
    <p>
      <div id="comment-react">
        <%= link_to "/react/#{@thought.class.name}/#{@thought.id}/agree", id:'t-concordo', title:'concordo', class:'btn btn-default btn-circle btn-lg', remote:true do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>
        <% end %>
        <%= link_to "/react/#{@thought.class.name}/#{@thought.id}/love", id:"t-amei", title:"amei", class:"btn btn-default btn-circle btn-lg", remote:true do %>
          <i class="glyphicon glyphicon-heart"></i>
        <% end %>
        <%= link_to "/react/#{@thought.class.name}/#{@thought.id}/disagree", id:'t-discordo', title:"discordo", class:"btn btn-default btn-circle btn-lg", remote:true do %>
          <i class="glyphicon glyphicon-thumbs-down"></i>
        <% end %>
      </div>
    </p>
    </div>
  </div>
  <hr />
  <div class="container">
    <%= form_with url: create_observation_path(@thought.id), local: true, class:"row form-inline margin-bottom" do |form| %>
      <div class="col-md-6">
        <%= form.text_area :comment, class:"form-control", style:"min-width:100%;", rows:"3"%>
      </div>
      <div class="col-md-2 align-right">
        <button type="submit" class="btn btn-info">make an observation</button>
      </div>
    <% end %>
  </div>
  <h3>Observations(<%= @observations.length %>)</h3>
  <% if @observations.length > 0 %>
    <% @observations.each do |observation| %>
      <div class="row">
        <div class='col-md-8'>
          <div class="panel panel-default">
            <div class="panel-body">
              <p><strong><%= observation.user.email %>:</strong>
              <p><%= observation.comment %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<script>
<% if @thought.react?(current_user) %>
  switch("<%= @thought.react?(current_user).reaction %>") {
    case 'agree':
      $('#t-concordo').attr({ href:"/react-delete/<%= @thought.class.name %>/<%=@thought.id %>",
                              class:"btn btn-info btn-circle btn-lg"
                      });
      break;
    case 'love':
      $('#t-amei').attr({ href:"/react-delete/<%= @thought.class.name %>/<%=@thought.id %>",
                          class:"btn btn-danger btn-circle btn-lg"
                       });
      break;
    case 'disagree':
      $('#t-discordo').attr({ href:"/react-delete/<%= @thought.class.name %>/<%=@thought.id %>",
                              class:"btn btn-warning btn-circle btn-lg"
                      });
      break;
  }
<% end %>
</script>